### ISSUE TITLE
Crashed on Nexus 6p

### ISSUE THREAD

**Issue by raghunandankavi2010** [Kelin-Hong/CalendarListView#3]
I just installed the app and was opening the home screen and suddenly the sample .apk fiel crashed.

Crash log i could extract from Android Studio

```
    Process: com.kelin.calendarlistview, PID: 25736
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.removeView(android.view.View)' on a null object reference
                                                                            at com.kelin.calendarlistview.library.CalendarView$5.onAnimationEnd(CalendarView.java:303)
                                                                            at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                            at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                            at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by raghunandankavi2010** [comment]
Also can the sample app contain english text. Its rather hard to make out what is displayed on the screen since its not english.
