### ISSUE TITLE
Crashed when I run the Sample and give one DayNews data a month

### ISSUE THREAD

**Issue by KevinStoneCode** [Kelin-Hong/CalendarListView#5]
I run your sample code and give one DayNews data a month,then App crashed. Can the bug be fixed or How can I avoid it. Thanks.

您好，我使用你的範例(從github下載再import到AS)，將資料改成一個月給一筆時，App 就會 Crash。請問這bug有辦法修正嗎?或是有方法可以避免呢?謝謝

---

part of source code

```
private TreeMap<String, List<ListModel>> listTreeMap = new TreeMap<>();

private void onListDataLoadFinish(String date){
        Calendar calendar = getCalendarByYearMonthDay(date);
        String key = CalendarHelper.YEAR_MONTH_FORMAT.format(calendar.getTime());

        List<ListModel> datas = new ArrayList<>();
        for(int i=5; i<6; i++) {
            ListModel model = new ListModel();
            model.setTitle("test" + i);
            if (i < 10) {
                model.setEventDate(key + "-0" + i);
            } else {
                model.setEventDate(key + "-" + i);
            }
            datas.add(model);
        }

        for (ListModel element:datas) {
            //获取数据的日期
            String day=element.getEventDate();
            //给listTreeMap 添加数据
            if (listTreeMap.get(day) != null) {
                List<ListModel> list = listTreeMap.get(day);
                list.add(element);
            } else {
                List<ListModel> list = new ArrayList<ListModel>();
                list.add(element);
                listTreeMap.put(day, list);
            }
        }

        dayNewsListAdapter.setDateDataMap(listTreeMap);
        dayNewsListAdapter.notifyDataSetChanged();
    }

-----------------------------------------------------------------------------
// in build.gradle
compile 'com.kelin.calendarlistview:library:1.0.1'
```

---

the Logcat:
08-31 14:49:41.549 3868-3868/com.kelin.calendarlistview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.kelin.calendarlistview, PID: 3868
                                                                          java.util.ConcurrentModificationException
                                                                              at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                              at com.kelin.calendarlistview.library.PinnedHeaderListView.onScrollStateChanged(PinnedHeaderListView.java:180)
                                                                              at android.widget.AbsListView.reportScrollStateChange(AbsListView.java:4339)
                                                                              at android.widget.AbsListView$FlingRunnable.endFling(AbsListView.java:4470)
                                                                              at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4563)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:211)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by Kelin-Hong** [comment]
不好意思，最近比较忙，回复晚了，“將資料改成一個月給一筆時”是指一个月只有一个数据吗？😁

**Comment by KevinStoneCode** [comment]
是的，
另外發現，在資料正常的時候，操作上第一次載入calendarlistview之後什麼也不做，然後隨便點一個calendar上的日期也會發生同樣的錯誤，如果第一次載入後有做其他操作(例如在下面的listview上滑動幾下)就不會有問題，不過我是用Fragment，不曉得有沒有關聯。

目前我的處理方式是在
com.kelin.calendarlistview.library.PinnedHeaderListView.onScrollStateChanged
改成

`

```
public void onScrollStateChanged(AbsListView view, int scrollState) {
    if (mOnScrollListeners != null && mOnScrollListeners.size() > 0) {
        try {
            for (OnScrollListener item:mOnScrollListeners){
                item.onScrollStateChanged(view, scrollState);
            }
        } catch (ConcurrentModificationException ex){
            ex.printStackTrace();
        }
    }
}
```

`

來防止app crash，只是不曉得對calendarlistview的操作上會不會有什麼影響?

謝謝
